
exec-once = waybar 
exec-once = swaync 
exec-once = awww-daemon 
exec-once = hypridle
exec-once = sleep 2 && wl-paste --type text --watch cliphist store
exec-once = sleep 2 && wl-paste --type image --watch cliphist store
exec-once = snappy-switcher --daemon
exec-once = kdeconnectd
exec-once = nwg-dock-hyprland -i 38 -c ~/.config/rofi/launcher.sh -hl "top"  -p "left" -d